rocketmq:
  producer:
    isOnOff: on
    groupName: ${spring.application.name}
    namesrvAddr: 127.0.0.1:9876
    maxMessageSize: 4096
    sendMsgTimeout: 3000
    retryTimesWhenSendFailed: 3
  consumer:
    isOnOff: on
    groupName: ${spring.application.name}
    namesrvAddr: 127.0.0.1:9876
    topics: demoTopic~*
    consumeThreadMin: 20
    consumeThreadMax: 40
    consumeMessageBatchMaxSize: 1
management:
  security:
    enabled: false
